name: Get Advent of Code Input

on:
  schedule:
    # Runs at 05:00 UTC every day from December 1st to December 25th
    - cron: '0 5 1-25 12 *'
  workflow_dispatch:
    inputs:
      day:
        description: 'Day of Advent of Code to fetch input for'
        required: true
        default: '1'

jobs:
  get-input:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get Advent of Code input
      id: get_input
      run: |
        day=${{ github.event.inputs.day }}
        year=$(date +%Y)
        mkdir -p day-$day
        curl -H "Cookie: session=${{ secrets.AOC_SESSION }}" \
             https://adventofcode.com/$year/day/$day/input -o day-$day/input.txt
        echo "::set-output name=day::$day"

    - name: Display input file
      run: cat day-${{ steps.get_input.outputs.day }}/input.txt

    - name: Commit and push input file
      uses: EndBug/add-and-commit@v9
      with:
        author_name: ${{ github.actor }}
        author_email: ${{ secrets.EMAIL }}
        message: "Add input for day ${{ steps.get_input.outputs.day }}"
        add: "day-${{ steps.get_input.outputs.day }}/input.txt"
        push: true
        github_token: ${{ secrets.GH_PAT }}